/var/log/vusmartmaps/vusoft_logging.????-??-??
{
    rotate 10
    maxsize 50M
    hourly
    copytruncate
    compress
    nodateext
    missingok
    dateformat -%Y%m%d_%H%M%S
    notifempty
    maxage 10
    su root root
    create 777 root root
    prerotate
        find /var/log/vusmartmaps -name "vusoft_logging.*" -mtime +10 -delete
    endscript
}
