apiVersion: v1
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: OTV6NXNqTVpMRTZxUWpSclZyVkd0T2dlM3IxazhwNGE=
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: aHR0cHM6Ly90cmFlZmlrL3JlYWxtcy92dW5ldC9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC90b2tlbg==
  GF_AUTH_TOKEN_ROTATION_INTERVAL_MINUTES: MTQ0MA==
  GF_DATABASE_HOST: dGltZXNjYWxlZGI=
  GF_DATABASE_NAME: dnVncmFmYW5h
  GF_DATABASE_PASSWORD: dnVzbWFydA==
  GF_DATABASE_USER: dnVzbWFydA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: nairobi-secret-spc
  namespace: {{ .Release.Namespace }}
type: Opaque
