{{- if (include "grafana.createAdminSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: nairobi-secret
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.secretlabels.create }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: grafana
  {{- end }}
type: Opaque
data:
  postgres_password: {{ ternary (randAlphaNum 10) .Values.admin.password (empty .Values.admin.password) | b64enc | quote }}
{{- end }}
