apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.reporterservice.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.reporterservice.port }}
      targetPort: {{ .Values.reporterservice.targetPort }}
      name: http
  selector:
    app: {{ .Values.reporterservice.appLabel }}
    organization: vunet
