apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-secrets
  labels:
  {{- include "cairo.labels" . | nindent 4 }}
data:
  credentials: {{ .Values.global.awsSecrets.credentials | toYaml | indent 1 }}
