apiVersion: v1
kind: Secret
metadata:
  name: fcm-secret
type: Opaque
data:
  fcm-config: |
    eyJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsInByb2plY3RfaWQiOiAidnVzbWFydG1hcHMtcHJv
    ZCIsInByaXZhdGVfa2V5X2lkIjogImNhYjY2ZWIzMmQ2NDgyZGI3ZTc2ZjMxYmRjYjYzOGQ5Mjk5
    M2UxNjIiLCJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2
    UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRG9Yc1BzQ3AwVXhx
    LzJcbjhpM1IrZERGMGRVUzZoTEZTQzVuUys5SzNtNzRiblRtR2tENkY1Y3JDeWxoYzVQeTlDNHly
    akFoejhiajVld0tcbjJmMWprRTRLb0xxMUYvQldOZkpiVmlyM1MyM0xnSnZPeVAwbUk0MkgvRk9l
    R2VzZ3daeWVCWFF3OE9uWHRRWTlcbnNxS2hlRHF5K1RxWmZITjFyU2NsTjI1aG54ZU5uMVN3SXF5
    enRhMUxtYlpaTW1UZEViL3p4NzdDbCtpSUh0TTRcbldadVl1aWFnNjI3cjNyQ1ZaNURYWU5xbWc0
    OVBEMk9pRmR1TGxmU0ZmVEJiaXlaS0VFVDFzMXdXZjNmQzI4RlVcbjVZS3NqV21ldncvaFEwczNq
    cWRBSzF2aFBWRTlnWlBOL0gvTHJCNDRjRExLRWU0bXNGUXZDYkJMMUZNS1piT2xcbk05VEp2Wmpa
    QWdNQkFBRUNnZ0VBRS9ZR0N3b0xYZHhHZytaZ2FNUDJ1dk9RUS9CdkhkcmFQNTNlaDdZdFhySndc
    bllNN2JDNURJdDlZYzN5WDBUTi9NY3lhUzlHaWFtM3VtQi9XYlpuamdOMW9BeCtzdlJseWFmZDJj
    VWNOOVFrakJcbk9hVjYxNUtneHhCMkoyUHZGcENETVhEaS93eEc3alI2L1lSUm82REdIQmM4UVRD
    WFk0RzFGZVdaMmhGMlRzQTVcbjlGMk1pb3pNUVRSYXNDZjJPa1ZhdE4yY05Ba0J1RittMHdRM1ZB
    NmQ4Zm9wSXp2UVV1RUhTVFRyeFpIUEVWcVJcbktxci83SFZMR0I0NXRleVdMVzVra3grejAzY1V5
    OXRKazMyeGorT0ZPdkFadnBZVXNab2hJRHBMMFhHOEFkbUJcbnU2dHhUVlNvM0N2bXBtZk1QeG9s
    QTNIdkdsY2tHTEJISFAxNmUzUGtYUUtCZ1FEc3VqcEhzeU1CQldXMFBnbkhcbituNS9meXgvRm5n
    TUllQzg0UjM5L1V0c1lPTmhDSldJa1Y3Slo5bEJYZzZGRk9tNkhsckI3ZHppWEVMbHVENWRcbkxX
    TWNERHJNemgzZEhvcDNsaWRPVUhZRUl3UCs5VFNhbTM2MVp6RUhSMkwvaEJjV1JFSXgxSDJ2TWVU
    cFZQSDFcbm95Q2VEK1VLOFN1MkptcGM4ZjA0Y01JVTFRS0JnUUQ3U2JtbklGMmRlKytDS3d0bTR4
    SlpXbWsva3laLzdMajNcbjRMVFhjb2hGa0JlOHMzd2JHcWIrYkpsQktFZ1ZmRkN0clE3WVl5Mm1N
    NVM0eWVwZDNTTHZFZWdEL2dEayt6QjRcbm9FeFEwbWhhN0pjZmZOUGtiY2R6YXMwUGIvcytZaGly
    ZXVzY0EwR1JyQTJLVDNib1hVRnN4U1RIdUJJOHlxNlVcbkVJMmlxUG1GOVFLQmdIR096QkpFL28r
    bzFTYm5jNjI0bmlIdkVadE5YZjBENjFqdjdJRkFsb1BBM3BKWG1kUFBcbldGYnBPRERCTzluZk5G
    ZVI1QnVQVFJ4UkFjNU0yYTI4N2dRd1lheUpXNDRNN29ON1JoT3RTVSttdEc0RGxsNXNcbkpSWkVF
    Q0xidmNPd3k1cGsyQlFyU0xkWUNlVmNXRTFyR1dSNVgzZ21STCsySWVQQU9hWnZnTXFaQW9HQU9D
    Z3pcbnV5dTZnQlZRWXpDbmJhalZVdTZua3JPWjZRRElIVzAwUE9tMWxvWXJKOXFjbzVvRE05eWxL
    ekNMVzNIYXZkVnNcbitlTEFNdUpZSEN2VG1vSnU2aXFBUlZRZ2N3dkh1MDFuZ0xCazdkenRzUFcr
    ak5BVHdMRmZmbEd5UGpEQi9xQ0xcbnBrajhBRWdKQnAzWG52b29RdHlUNmFZelBTNjJjUlI1OHAz
    OGxYa0NnWUVBdHViYXlUUnViaXFXZktkTWpIcE5cbjlvVk1SVmxrNG02UG1rNTZ4TFEvRi96WWRz
    WW5DRGd2YXk2TXNFZkQrNmhDeEphcU1uK0J3WlpWSzZ3OWlMQVFcblo2VHZGdkJ4Z0dHNG5raWg0
    R0ZXVFZsdXFlUDdpUmx2Ymw0MHNabVl2dWZKeVJOWlJtU1FOSytmcFRNZFd3SHpcbnQxdkQ5ZW8r
    T0daWmRPbm8weWdjTytNPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwiY2xpZW50X2Vt
    YWlsIjogImZpcmViYXNlLWFkbWluc2RrLXJqbmI2QHZ1c21hcnRtYXBzLXByb2QuaWFtLmdzZXJ2
    aWNlYWNjb3VudC5jb20iLCJjbGllbnRfaWQiOiAiMTEyOTQxODI2NzI1OTE2NzY1MDA5IiwiYXV0
    aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLCJ0b2tl
    bl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCJhdXRoX3Byb3Zp
    ZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3Yx
    L2NlcnRzIiwiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5j
    b20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1yam5iNiU0MHZ1c21h
    cnRtYXBzLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1bml2ZXJzZV9kb21haW4iOiAi
    Z29vZ2xlYXBpcy5jb20ifQ==    