{{- if .Values.pvMapping }}
{{- $namespace := .Release.Namespace }}
{{range $i, $e := .Values.pvMapping}} # list of nodeNames comes from launcher sizing file 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{$i}}-pv
  annotations:
    helm.sh/resource-policy: keep
spec:
  capacity:
    storage: {{ $e.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $e.storageClass }} 
  local:
    path: {{ $e.hostPath }}/{{ $e.dirPath }}  # Local path on each node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "kind-control-plane"  # Use node name from list
  claimRef:
    name: "{{$i}}"  # Name of the PVC that will claim this volume
    namespace: {{ $namespace }}
---
{{- end }}
{{- end }}
