apiVersion: v1
kind: Secret
metadata:
  name: secret-env
  annotations:
    "helm.sh/hook-weight": "-10"
data:
  access_key: {{ .Values.secrets.access_key }}
  secret_key: {{ .Values.secrets.secret_key }}
  key_hex: {{ .Values.persistence.key }}
