
{{- if  .Values.secret.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace:  {{ template "traefik.namespace" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  tls.key: {{ .Values.secret.tlsKey }}
  tls.crt: {{ .Values.secret.tlsCrt }}

{{- end }}

---

{{- if  .Values.secret.auth.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.auth.name }}
  namespace:  {{ template "traefik.namespace" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  users: {{ .Values.secret.auth.data.users }}
{{- end }}

