apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secret.data.KEYCLOAK_ADMIN_PASSWORD | b64enc }}
  KEYCLOAK_DATABASE_PASSWORD: {{ .Values.secret.data.KEYCLOAK_DATABASE_PASSWORD | b64enc }}
  KEYCLOAK_MANAGEMENT_PASSWORD: {{ .Values.secret.data.KEYCLOAK_MANAGEMENT_PASSWORD | b64enc }}
