apiVersion: v1
kind: Service
metadata:
  labels:
    organization: vunet
    io.kompose.service: keycloak
  name: {{ .Values.keycloakService.name }}
spec:
  ports:
    - name: "8080"
      port: {{ .Values.keycloakService.ports.port }}
      targetPort: {{ .Values.keycloakService.ports.targetPort }}
    - name: "health-check"
      port: {{ .Values.keycloakContainer.ports.healthCheckPort}}
      targetPort: {{ .Values.keycloakContainer.ports.healthCheckPort}}
  selector:
    organization: vunet
    io.kompose.service: keycloak
status:
  loadBalancer: {}

