apiVersion: v1
data:
  VUSMART_USERNAME: dnVzbWFydG1hbmFnZXI=
  VUSMART_PASSWORD: VnVuZXQjMTIzNA==
  DNS_PASSWORD: VnVuZXQlMjMxMjM0
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: telegraf-vusmart
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: vusmart-secret
  namespace: vsmaps
type: Opaque
