apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    organization: vunet
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8778
      name: jmx
    - port: 9092
      name: broker
    - port: 9094
      targetPort: {{ .Values.externalServicePort }}
      name: broker-tls
    {{- if .Values.prometheus.jmx.enabled }}
    - port: {{ .Values.prometheus.jmx.port }}
      name: metrics
    {{- end }}
  selector:
    organization: vunet
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}
