apiVersion: v1
kind: ConfigMap
metadata:
  name: vublock-vunode-config
data:
  vunode_config.yml: |-
    {{- $celerySectionPrinted := false }}
    {{- range $key, $value := .Values.vublock.celery }}
      {{- if $value.enable }}
        {{- if not $celerySectionPrinted }}
    celery:
           {{- $celerySectionPrinted = true }}
        {{- end }}
        {{- $queueName := "" }}
        {{- $appPath := "" }}
        {{- if or (eq $key "vublock-config") (eq $key "vublock-configuration") }}
        {{- $appPath = "daq.services.vublock_configuration.vublock_configuration_celery" }}
        {{- $queueName = "vublock_config_queue" }}
        {{- else if or (eq $key "vublock-diag") (eq $key "vublock-diagnostics") (eq $key "vublock-diagnostic") }}
        {{- $appPath = "daq.services.vublock_diagnostic.vublock_diagnostic_celery" }}
        {{- $queueName = "vublock_diagnostic_queue" }}
        {{- end }}
        {{- if ne $queueName "" }}
      -
        name: {{ $queueName }}
        args: -A {{ $appPath }} worker -Q {{ $queueName }} --max-tasks-per-child=1024 --detach --loglevel=error --pidfile=/tmp/celery.%n.{{ $key }}.pid --logfile=/tmp/celery.%n.{{ $key }}.log --autoscale={{ $value.autoscale }}
        include_in_global_instance: False
        {{- end }}
      {{- end }}
    {{- end }}

    nodes:
      -
        name: vublock
        {{- $sectionPrinted := false }}
        {{- range $svc_key, $svc_value := .Values.vublock.services }}
          {{- if $svc_value.enable }}
          {{- if not $sectionPrinted }}
        services:
          {{- $sectionPrinted = true }}
          {{- end }}
          -
            {{- if or (eq $svc_key "vublock-config") (eq $svc_key "vublock-configuration") }}
            name: "vublock_configuration"
            {{- else if or (eq $svc_key "vublock-diag") (eq $svc_key "vublock-diagnostics") (eq $svc_key "vublock-diagnostic") }}
            name: "vublock_diagnostic"
            {{- end }}
          {{- end }}
        {{- end }}
