# vulauncher will update this section while deployment
vunet:
  imageServer: &imageServer ghcr.io
    #imageServer: &imageServer vunet-registry:5000
  imageName: &imageName vunetsystems/cairo
  imageTag: &imageTag 2.16.901
    #imageTag: &imageTag 2.16.901
  imagePullSecrets:
    - name: ghcr-login-secret
  # cpu and memory min and max values
  resources: &resources
    limits:
      cpu: "0.5"
      memory: 2Gi
    requests:
      cpu: "0.3"
      memory: 500Mi
  # priority node labels
  nodeAffinity: &nodeAffinity {}
  # tolerations
  tolerations: &tolerations []
  # number of pods to run
  replicas: &replicas 1
  # pvc size that will be claimed. For vuinterface we will use default section. All others
  # will be zero value
  hot:
    size: &hotSize ""
    enabled: &hotEnabled false
    encrypted: &hotEncrypted false
    storageclass: &hotStorageClass ""
  warm:
    size: &warmSize ""
    enabled: &warmEnabled false
    encrypted: &warmEncrypted false
    storageclass: &warmStorageClass ""
  cold:
    size: &coldSize ""
    enabled: &coldEnabled false
    encrypted: &coldEncrypted false
    storageclass: &coldStorageClass ""
  default:
    size: &defaultSize ""
    enabled: &defaultEnabled false
    encrypted: &defaultEncrypted false
    storageclass: &defaultStorageClass ""
  default-replica:
    size: &defaultReplicaSize ""
    enabled: &defaultReplicaEnabled false
    encrypted: &defaultReplicaEncrypted false
    storageclass: &defaultReplicaStorageClass ""
  host:
    size: &hostSize ""
    enabled: &hostEnabled false
    encrypted: &hostEncrypted false
    storageclass: &hostStorageClass ""
  # ghcr credentials
  pullSecretName: &pullSecretName ghcr-login-secret
  # loadbalancer IP information
  loadbalancer: &loadbalancer []
fullnameOverride: "vuinterface"
securityContext:
  privileged: false
  allowPrivilegeEscalation: false # Prevent privilege escalation
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
serviceAccount:
  create: true
  name: vunode
  automountServiceAccountToken: true
posthook:
  repository: *imageServer
  imageName: vunetsystems/kubectl
  imageTag: v2.15.0
global:
  extraEnvVars: []
env:
  - name: TRAEFIK_IPS
    value: 216.48.185.161
  - name: VSMAPS_DOMAIN
    value: 216.48.185.161
  - name: HOT_DISK_NAME
    value: default_encrypted_disk
  - name: WARM_DISK_NAME
    value: warm_encrypted_disk
  - name: COLD_STORE_ENABLED
    #value: True
    value: "True"
vuinterface:
  args:
    - /bin/bash
    - -c
    - cd /home/vunet/workspace/cairo; gunicorn -c mickey/core/gunicorn.conf.py -b 0.0.0.0:8888 -k uvicorn.workers.UvicornWorker mickey.core.asgi:application  --workers 10  --max-requests 1000 --max-requests-jitter 2000 --keep-alive 7 --timeout 850
  migrate:
    args:
      - /home/vunet/workspace/cairo/mickey/db_migrations.sh
  podAntiAffinityPreset: ""
  # nodeAffinity
  affinity:
    nodeAffinity: *nodeAffinity
  # toleration for vuinterface pods
  tolerations: *tolerations
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
  # number of pods that will be created for vuinterface
  replicas: *replicas
  # resource limits for vuinterface pods
  resources: *resources
  # image pull secret to fetch the image
  imagePullSecret:
    - name: *pullSecretName
  pullPolicy: IfNotPresent
  repository: *imageServer
  name: *imageName
  tag: *imageTag
  # vuinterface storage information
  volumeClaims:
    datalake:
      requests:
        storage: *defaultSize
    vsmapsLogs:
      requests:
        storage: *defaultSize
        # image pull secret to fetch the image
    imagePullSecret:
      - name: *pullSecretName
    # vuinterface storage information
    volumeClaims:
      datalake:
        requests:
          storage: *defaultSize
      vsmapsLogs:
        requests:
          storage: *defaultSize
vuinterfaceSvc:
  ports:
    - name: vuinterface
      port: 8888
      protocol: TCP
      targetPort: 8888
  type: ClusterIP
pvMapping: {}
kubectlResources:
  requests:
    cpu: "50m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "200Mi"
migrate:
  resources:
    requests:
      cpu: 300m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
