apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-tenant
  namespace: vsmaps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-storage

