---
apiVersion: v1
data:
  {{- $files := .Files }}
  {{- range tuple "create_data_ingestion_tables.py" }}
  {{ . }}: |-
        {{ $files.Get . | nindent 8 }}
  {{- end }}
kind: ConfigMap
metadata:
  name: data-ingestion-tables-cm
