apiVersion: v1
kind: Secret
metadata:
  name: kafka-connect-secret
  annotations:
    "helm.sh/hook-weight": "-10"
data:
  CONNECT_INTERNAL_KEY_CONVERTER: b3JnLmFwYWNoZS5rYWZrYS5jb25uZWN0Lmpzb24uSnNvbkNvbnZlcnRlcg==
  CONNECT_INTERNAL_VALUE_CONVERTER: b3JnLmFwYWNoZS5rYWZrYS5jb25uZWN0Lmpzb24uSnNvbkNvbnZlcnRlcg==
  CONNECT_KEY_CONVERTER: b3JnLmFwYWNoZS5rYWZrYS5jb25uZWN0Lmpzb24uSnNvbkNvbnZlcnRlcg==
  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: aHR0cDovL2thZmthLWNsdXN0ZXItY3Atc2NoZW1hLXJlZ2lzdHJ5OjgwODE=
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: aHR0cDovL2thZmthLWNsdXN0ZXItY3Atc2NoZW1hLXJlZ2lzdHJ5OjgwODE=