apiVersion: v1
kind: Secret
metadata:
  name: secret-certs
  annotations:
    "helm.sh/hook-weight": "-10"
data:
  server.crt: |-
{{ .Files.Get "secrets/hs-certs/vunet-hyperscale-cert.pem" | b64enc | indent 4 }}
  server.key: |-
{{ .Files.Get "secrets/hs-certs/vunet-hyperscale-key.pem" | b64enc | indent 4 }}
  rootCA.crt: |-
{{ .Files.Get "secrets/hs-certs/vunet-ca-cert.pem" | b64enc | indent 4 }}