apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-keeper.fullname" . }}-hl
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 9444
      name: raft
  selector:
    {{- include "clickhouse-keeper.selectorLabels" . | nindent 4 }}
