apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name  }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "minio-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
