apiVersion: v1
data:
  AIRFLOW_PASSWORD: YWlyZmxvdw==
  AIRFLOW_USERNAME: YWlyZmxvdw==
  CHATGPT_API_KEY: c2stbHJ2OEdVZGJUNUpoaHY3bEEyOGdUM0JsYmtGSk9qeFZKYVNTa2w5aEZzYUtySTM3
  GRAFANA_API_KEY: ZXlKcklqb2lTSFpEU0ZwWlpqTmxjbFJ4UVc5b1pYWlJaMHhLWVZkR1JteFNlRTVoTjJNaUxDSnVJam9pYW1sMGFHVnphQ0lzSW1sa0lqb3hmUT09
  GRAFANA_USERNAME: dnVuZXRfcm9vdA==
  GRAFANA_PASSWORD: TWF4Izc4MTQ=
  IDP_USER_MANAGEMENT_TOKEN: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklqWkRNakU1UkRWR01URXhPRUZDUkVZNVJFWTRRVFUwTmpnd09VRkJRVFkxSWl3aWRIbHdJam9pWVhRcmFuZDBJbjAuZXlKdVltWWlPakUyT0RNNE1USXpNelFzSW1WNGNDSTZNVGN4TlRNME9ETXpOQ3dpYVhOeklqb2lhSFIwY0hNNkx5OHpOQzR4TURBdU1qVXlMakkwT0M5cFpDSXNJbUYxWkNJNkluWjFibVYwU1dSd1gyRndhU0lzSW1Oc2FXVnVkRjlwWkNJNkluWjFibVYwU1dSd1gyRndhVjl6ZDJGbloyVnlkV2tpTENKemRXSWlPaUprTldFMFpqazBOUzAxTkRNNUxUUTVPRGN0WVRjNFlTMHlNalprWVRnMVpUVTFNR0VpTENKaGRYUm9YM1JwYldVaU9qRTJPRE00TVRJd09ERXNJbWxrY0NJNklteHZZMkZzSWl3aWNtOXNaU0k2SW5aMWJtVjBPakU2YVdRNmFXUndZV1J0YVc0aUxDSnVZVzFsSWpvaVpHOWZibTkwWDNSdmRXTm9JaXdpYW5ScElqb2lNRFl3TkRKRFJEazFORGMwUmtaRk1FUkZSVEJGUWpnNE1qazBOems1UWpBaUxDSnphV1FpT2lJeFFqRkRNRFE0TVRrM05FSkNOa1JETVRsR1JqZzFPVEl3T0RSRFFUY3pSaUlzSW1saGRDSTZNVFk0TXpneE1qTXpOQ3dpYzJOdmNHVWlPbHNpZG5WdVpYUkpaSEJmWVhCcElsMHNJbUZ0Y2lJNld5SndkMlFpWFgwLkZ5T3RWY3FpNVZSZWtzam1LXzBuQUtleFRaODBkRUF1UVVLb0JDSHQxZnZkeFBDZlZzSjQ3ZkxDazFBb1Z1Mmc0U2drakVfU2xrc2xTVVJ4ODcxVW9yU2M0T09OeDhOYkU1TDRyS2I0eDlKWjJweER6MVFyZ09QaVVBS0RHcXJqMUQteTBtQVFHTVlZT2ZDUkIyQ0hKdFd4YWdfQXRyQ1oxNlY3X3NhTTFGb3AxaVlfT1FxU3RtU2MwTDZGbm1Oa2lscU4wVmk1SGNGN0QzSnE5M2FhcTNORm1EeWtOOEFpMDhGR2lzRUkxamRsMm1yaWdPaS1CSmVJYk93RlU1RmQ3djRrbTdMSWNtc3RxUUc5ZVpuUjY0TEhNVnB3c1VwVzNrMDFodUR2VUoxWmVzRjBMeW02c0xCdF9Ta0EzSndBVVlJWk9ac0F3UnAyYUlQcENZR1NlZw==
  INTERNALDB_CREDENTIALS_PATH: L2hvbWUvdnVuZXQvc3JjL2RlbnZlci9kYi5pbmk=
  KEYCLOAK_CLIENT_SECRET_KEY: N211WGdDMlh2aEFBTjg3ME94bDYxOGhVVVlFS2J2cmw=
  MINIO_ACCESS_KEY: bWluaW8=
  MINIO_SECRET_KEY: bWluaW8xMjM=
  POSTGRES_PASSWORD: dnVzbWFydA==
  RESOURCE_SERVER_INTROSPECTION_KEY: NGExYWE4N2ItOGNiOC02MjA2LTBlYTMtYThmYWQwMDhmNjc3
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: denver-env-secret
  namespace: {{ .Release.Namespace }}
type: Opaque