apiVersion: v1
data:
  VUSMART_USERNAME: dnVzbWFydG1hbmFnZXI=
  VUSMART_PASSWORD: VnVuZXQjMTIzNA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: telegraf-infra
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: infra-secret
  namespace: vsmaps
type: Opaque