apiVersion: v1
data:
  MINIO_ACCESS_KEY: bWluaW8=
  MINIO_SECRET_KEY: bWluaW8xMjM=
  CH_USER: dnVzbWFydG1hbmFnZXI=
  CH_PASSWORD: VnVuZXQjMTIzNA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: orchestrator-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
