apiVersion: v1
data:
  GRAFANA_API_KEY: ZXlKcklqb2lSbXRtUWtwaVprbFFSRmhTUm5OU05XNVpjMkp0UWpjeFlsUmpOelphTlZraUxDSnVJam9pYm1semFHRnVkR3RsZVhNaUxDSnBaQ0k2TVgwPQ==
  GRAFANA_USERNAME: dnVuZXRfcm9vdA==
  GRAFANA_PASSWORD: TWF4Izc4MTQ=
  MINIO_ACCESS_KEY: bWluaW8=
  MINIO_SECRET_KEY: bWluaW8xMjM=
  ORCHESTRATION_CLIENT_ID: b3JjaGVzdHJhdGlvbi1zZXJ2aWNl
  ORCHESTRATION_CLIENT_SECRET: YThjWmZCQjhTM09rdWc0OHNrOTBUdlVhY0FIbzM1Tnc=
  IDP_GET_TOKEN_URL: aHR0cDovL2tleWNsb2FrOjgwODAvcmVhbG1zL3Z1bmV0L3Byb3RvY29sL29wZW5pZC1jb25uZWN0L3Rva2Vu
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: vublock-store-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
