apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cairo.fullname" . }}-cairo
  labels:
    app: vuinterface
    managedBy: vunet
  {{- include "cairo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vuinterface.replicas }}
  selector:
    matchLabels:
      app: vuinterface
      managedBy: vunet
      {{- include "cairo.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: vuinterface
        managedBy: vunet
        {{- include "cairo.labels" . | nindent 8 }}
      annotations:
        {{- include "cairo.annotations" . | nindent 8 }}

    spec:
      {{- with .Values.vuinterface.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vuinterface.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.vuinterface.podAntiAffinityPreset "component" "grafana" "context" $) | nindent 10 }}
        {{- with .Values.vuinterface.affinity.nodeAffinity }}
        nodeAffinity:
            {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
      - name: vuinterface
        args: {{- toYaml .Values.vuinterface.args | nindent 8 }}
        env:
        {{- if .Values.env }}
        {{- include "common.tplvalues.render" (dict "value" .Values.env "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.global.extraEnvVars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.securityContext }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: vuinterface-config
        - secretRef:
              name: vuinterface-secret
        - configMapRef:
            name: {{ include "cairo.fullname" . }}-vunet-env
        image: {{ .Values.vuinterface.repository }}/{{ .Values.vuinterface.name }}:{{ .Values.vuinterface.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.vuinterface.pullPolicy }}
        workingDir: /home/vunet/workspace/cairo
        {{- if .Values.vuinterface.resources }}
        resources: {{- toYaml .Values.vuinterface.resources | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 8888
        - containerPort: 443
          name: https
        volumeMounts:
                # - name: ca-vunodes
                #   mountPath: /etc/ssl/certs/vunet-ca-cert.pem
                #   subPath: vunet-ca-cert.pem
        - name: alert-rule-config
          subPath: alert_rules.yml
          mountPath: /home/vunet/workspace/cairo/configs/alert_rules.yml
        - name: aws-env
          mountPath: /home/vunet/.aws/credentials
          subPath: credentials
        - name: cairo-env
          mountPath: /home/vunet/workspace/cairo/.env
          subPath: .env
        - name: pem-volume
          mountPath: /etc/vunet/licence/private.pem
          subPath: private.pem
        - name: pem-volume
          mountPath: /etc/vunet/licence/public.pem
          subPath: public.pem
      {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: autoclasses-volume
          mountPath: /home/vunet/workspace/cairo/pluto/autoclasses/
        - name: telenode-volume
          mountPath: /home/vunet/workspace/cairo/pluto/telenode/
        - name: tmp-volume
          mountPath: /tmp
        - name: var-tmp-volume
          mountPath: /var/tmp
        - name: templates-volume
          mountPath: /home/vunet/workspace/cairo/mickey/vusoft/vumap/vublock/configuration/templates
        - name: vusmartmaps-logs
          mountPath: /var/log/vusmartmaps/
        - name: logging-config
          mountPath: /home/vunet/workspace/cairo/utilities/logging_conf
      {{- end }}
      initContainers:
      - name: migrate
        args: {{- toYaml .Values.vuinterface.migrate.args | nindent 8 }}
        command:
        - /bin/bash
        - -c
        env:
        {{- if .Values.env }}
        {{- include "common.tplvalues.render" (dict "value" .Values.env "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.global.extraEnvVars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.securityContext }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: vuinterface-config
        - secretRef:
              name: vuinterface-secret
        - configMapRef:
            name: {{ include "cairo.fullname" . }}-vunet-env
        image: {{ .Values.vuinterface.repository }}/{{ .Values.vuinterface.name }}:{{ .Values.vuinterface.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.vuinterface.pullPolicy }}
        workingDir: /home/vunet/workspace/cairo
        resources: {{- toYaml .Values.migrate.resources | nindent 10 }}
        volumeMounts:
        - name: aws-env
          mountPath: /home/vunet/.aws/credentials
          subPath: credentials
        - name: cairo-env
          mountPath: /home/vunet/workspace/cairo/.env
          subPath: .env
      {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: autoclasses-volume
          mountPath: /home/vunet/workspace/cairo/pluto/autoclasses/
        - name: telenode-volume
          mountPath: /home/vunet/workspace/cairo/pluto/telenode/
        - name: tmp-volume
          mountPath: /tmp
        - name: var-tmp-volume
          mountPath: /var/tmp
        - name: templates-volume
          mountPath: /home/vunet/workspace/cairo/mickey/vusoft/vumap/vublock/configuration/templates
      {{- end }}
      volumes:
              #- name: ca-vunodes
              #  configMap:
              #  name: ca-vunodes
      - configMap:
          name: alert-rule
        name: alert-rule-config
      - configMap:
          name: aws-secrets
        name: aws-env
      - configMap:
          name: {{ include "cairo.fullname" . }}-vunet-env
        name: cairo-env
      - name: pem-volume
        secret:
          secretName: licence-pem
      {{- if .Values.securityContext.readOnlyRootFilesystem }}
      - name: autoclasses-volume
        emptyDir: {}
      - name: telenode-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
      - name: var-tmp-volume
        emptyDir: {}
      - name: templates-volume
        emptyDir: {}
      - name: vusmartmaps-logs
        emptyDir: {}
      - name: logging-config
        configMap:
          name: vusoft-logging-conf
      {{- end }}
