apiVersion: v1
kind: Service
metadata:
  name: vuinterface
  labels:
    app: vuinterface
    managedBy: vunet
  {{- include "cairo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.vuinterfaceSvc.type }}
  selector:
    app: vuinterface
    managedBy: vunet
  {{- include "cairo.labels" . | nindent 4 }}
  ports:
	{{- .Values.vuinterfaceSvc.ports | toYaml | nindent 2 -}}
