apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cairo.fullname" . }}-vunet-env
  labels:
  {{- include "cairo.labels" . | nindent 4 }}
data:
  .env:  |- 
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.vuinterfaceConfig "context" $ ) |  replace ": " "=" | nindent 4  }}

