# vulauncher will update this section while deployment
vunet:
  # cpu and memory min and max values
  imageServer: &imageServer ghcr.io
  imageName: &imageName vunetsystems/keycloak
  imageTag: &imageTag 25.0.17
  resources: &resources
    limits:
      cpu: "0.5"
      memory: 2Gi
    requests:
      cpu: "0.3"
      memory: 500Mi
  # priority node labels
  nodeAffinity: &nodeAffinity {}
  # tolerations
  tolerations: &tolerations []
  # number of pods to run
  replicas: &replicas 1
  # pvc size that will be claimed. For redis we will use default section. All others
  # will be zero value
  hot:
    size: &hotSize ""
    enabled: &hotEnabled false
    encrypted: &hotEncrypted false
    storageclass: &hotStorageClass ""
  warm:
    size: &warmSize ""
    enabled: &warmEnabled false
    encrypted: &warmEncrypted false
    storageclass: &warmStorageClass ""
  cold:
    size: &coldSize ""
    enabled: &coldEnabled false
    encrypted: &coldEncrypted false
    storageclass: &coldStorageClass ""
  default:
    size: &defaultSize ""
    enabled: &defaultEnabled false
    encrypted: &defaultEncrypted false
    storageclass: &defaultStorageClass ""
  default-replica:
    size: &defaultReplicaSize ""
    enabled: &defaultReplicaEnabled false
    encrypted: &defaultReplicaEncrypted false
    storageclass: &defaultReplicaStorageClass ""
  host:
    size: &hostSize ""
    enabled: &hostEnabled false
    encrypted: &hostEncrypted false
    storageclass: &hostStorageClass ""
  # ghcr credentials
  pullSecretName: &pullSecretName ghcr-login-secret
  #
  # dependencies will be list of helm chart path, which would be required for the current
  # chart. We will install its dependant helm charts first, then current helm chart
  # will be installed
  dependencies:
    - "postgresql"
#adding values for deployment.yaml file

posthook:
  repository: *imageServer
  imageName: vunetsystems/kubectl
  imageTag: v2.15.0
keycloakDeployment:
  name: keycloak-deployment
  replicas: *replicas
keycloakContainer:
  adminUser: vunetadmin
  databaseHost: timescaledb-1
  databaseName: keycloak
  databaseUser: vusmart
  managementUser: vunet
  repository: *imageServer
  name: *imageName
  tag: *imageTag
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: *pullSecretName
  ports:
    containerPort: 8080
    healthCheckPort: 9000
#adding values for myservice.yaml
keycloakService:
  name: keycloak
  ports:
    port: 8080
    targetPort: 8080
resources: *resources
#requests:
#  cpu: "100m"
#  memory: "50Mi"
#limits:
#  cpu: "300m"
#  memory: "150Mi"

#adding values for mysecret.yaml file
secret:
  name: keycloak-secret
  data:
    KEYCLOAK_ADMIN_PASSWORD: Qwerty@123
    KEYCLOAK_DATABASE_PASSWORD: vusmart
    KEYCLOAK_MANAGEMENT_PASSWORD: Max#7814
# will remove the existing format and replace with anchor
nodeAffinity: *nodeAffinity
# keyPlaceholder: keycloak
# valuePlaceholder1: "True"

tolerations: *tolerations
podAntiAffinity:
  keyPlaceholder: app
  valuePlaceholder: store
  topologyKeyPlaceholder: kubernetes.io/hostname
securityContext:
  privileged: false
  allowPrivilegeEscalation: false # Prevent privilege escalation
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
serviceAccount:
  create: true
  name: keycloak
  automountServiceAccountToken: false
kubectlResources:
  requests:
    cpu: "50m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "200Mi"
